Modules:
  faction-fly:
    enabled: true
    displayName: "Faction fly"
    description: ["Enable fly in your faction"]
    icon: STONE
    tiers:
      1:
        multiplier: 1
        cost: 100
      2:
        multiplier: 2
        cost: 200
  more-damage:
    enabled: true
    displayName: "More Damage Faction"
    description: ["Deal more damage inside your faction"]
    icon: DIAMOND_SWORD
    tiers:
      1:
        multiplier: 1
        cost: 100
      2:
        multiplier: 2
        cost: 200
      3:
        multiplier: 3
        cost: 300
  less-damage:
    enabled: true
    displayName: "&6Less Damage Faction"
    description: ["&eTake less damage inside your faction", "&2C:"]
    icon: SHIELD
    tiers:
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300