TierTemplate:
  have:
    displayName: "&aTier {tier}"
    lore: ["&aYou already have this tier."]
    item: lime_stained_glass_pane
  nothave:
    displayName: "&cTier {tier}"
    lore: ["&cYou don't have this tier.", "&cCost: {cost}", "&cMultiplier: {multiplier}"]
    item: red_stained_glass_pane

Modules:
  faction-fly:
    enabled: true
    displayName: "&bFaction fly"
    lore: ["&bEnable fly in your faction"]
    item: QUARTZ
    tiers:
      1:
        multiplier: 0
        cost: 100
  more-damage:
    enabled: true
    displayName: "&6More Damage Faction"
    lore: ["&eDeal more damage inside your faction"]
    item: DIAMOND_SWORD
    enchantments:
      - SHARPNESS:5
    tiers:
      1:
        multiplier: 1
        cost: 100
      2:
        multiplier: 2
        cost: 200
      3:
        multiplier: 3
        cost: 300
  less-damage:
    enabled: true
    displayName: "&6Less Damage Faction"
    lore: ["&eTake less damage inside your faction"]
    item: SHIELD
    tiers:
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300
  tnt-vault:
    enabled: true
    displayName: "&6More TNT"
    lore: ["&6Increase your TNT Vault"]
    item: TNT
    tiers:
      0:
        multiplier: 1
        cost: 0
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300
  bigger-vault:
    enabled: true
    displayName: "&6More space"
    lore: ["&6Increase your vault size"]
    item: ENDER_CHEST
    tiers:
      0:
        multiplier: 1
        cost: 0
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300
  crop-growth:
    enabled: true
    displayName: "&6More food"
    lore: ["&eIncrease you crop growth rate"]
    item: WHEAT_SEEDS
    tiers:
      0:
        multiplier: 0
        cost: 0
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300
      4:
        multiplier: 90
        cost: 50
      5:
        multiplier: 99
        cost: 1000

  spawner-speed:
    enabled: true
    displayName: "&6More mobs"
    lore: ["&eIncrease your mob spawner spawning rate"]
    item: SPAWNER
    tiers:
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300
  xp-booster:
    enabled: true
    displayName: "&6XP Booster"
    lore: ["&eGain more XP inside your faction"]
    item: experience_bottle
    tiers:
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300
  more-member:
    enabled: true
    displayName: "&6More members"
    lore: ["&eIncrease your member size"]
    item: PLAYER_HEAD
    tiers:
      0:
        multiplier: 0
        cost: 0
      1:
        multiplier: 10
        cost: 100
      2:
        multiplier: 15
        cost: 200
      3:
        multiplier: 20
        cost: 300